package com.subaru.global.infotainment.gen2.harman;

import java.util.ArrayList;

/* loaded from: classes.dex */
public class HarmanOTAConst {
    public static final String API_CANCEL_DOWNLOAD = "cancelDownload";
    public static final String API_CHECK_FOR_UPDATE = "checkForUpdate";
    public static final String API_CLEAR_DATA = "clearData";
    public static final String API_GET_CURRENT_MAP_DETAILS = "getCurrentMapDetails";
    public static final String API_INFORM_AUTO_DOWNLOAD_STATUS = "informAutoDownloadStatus";
    public static final String API_INFORM_AUTO_UPDATE_STATUS = "informAutoUpdateStatus";
    public static final String API_INFORM_NETWORK_STATUS = "informNetworkStatus";
    public static final String API_KILL_AHA_SERVICE = "killAhaService";
    public static final String API_MAP_SUBSCRIPTION_DETAILS = "mapSubscriptionDetails";
    public static final String API_REMOVE_DEVICES = "removeDevices";
    public static final String API_REQUEST_ACCESSORY_FILE_TRANSFER_PROGRESS = "accessoryFileTransferProgress";
    public static final String API_RETRIEVE_AVAILABLE_MAP_REGIONS = "retrieveAvailableMapRegions";
    public static final String API_START_DOWNLOAD = "startDownload";
    public static final String API_STOP_AHA_SERVICE = "stopAhaService";
    public static final String ERROR_CODE_KEY = "errorCode";
    public static final String HARMAN_LIBRARY_APP_NAME = "MapOTA";
    public static final String INTENT_KEY = "ota_notify";
    public static final String JSON_ACCESSORY_TRANSFER_STATUS = "accessoryTransferStatus";
    public static final String JSON_APP_IDENTIFIER = "appIdentifier";
    public static final String JSON_APP_INFO = "appInfo";
    public static final String JSON_BASELINE_ID = "baselineID";
    public static final String JSON_CONTENT_TYPE = "application/json";
    public static final String JSON_DATA = "data";
    public static final String JSON_DEVICE_CODE = "deviceCode";
    public static final String JSON_DOWNLOAD_STATUS = "downloadStatus";
    public static final String JSON_ERROR_CODE = "errorCode";
    public static final String JSON_EXPIRY_DATE = "expiryDate";
    public static final String JSON_FROM_VERSION = "fromVersion";
    public static final String JSON_ID = "id";
    public static final String JSON_MAP_JSON = "mapJson";
    public static final String JSON_MODE = "mode";
    public static final String JSON_NDS_PRODUCT = "nds_product";
    public static final String JSON_NDS_REGION = "nds_region";
    public static final String JSON_NDS_REGION_ID = "id";
    public static final String JSON_NDS_REGION_NAME = "name";
    public static final String JSON_NOTIFY_STATUS = "notifyStatus";
    public static final String JSON_PRODUCTS = "products";
    public static final String JSON_PRODUCT_CODE = "productCode";
    public static final String JSON_PRODUCT_ID = "productID";
    public static final String JSON_PROGRESS = "progress";
    public static final String JSON_QUERY = "query";
    public static final String JSON_REGIONS = "Regions";
    public static final String JSON_REGION_ID = "regionID";
    public static final String JSON_REGION_NAME = "regionName";
    public static final String JSON_REQ = "req";
    public static final String JSON_RESP = "resp";
    public static final String JSON_RESP_CODE = "respCode";
    public static final String JSON_SERVICE_INFO = "serviceInfo";
    public static final String JSON_STATUS = "status";
    public static final String JSON_SUB_VERSION = "subVersion";
    public static final String JSON_SUPPLIER_ID = "supplierID";
    public static final String JSON_TO_VERSION = "toVersion";
    public static final String JSON_TYPE = "type";
    public static final String JSON_UPDATES = "Updates";
    public static final String JSON_VERSION = "version";
    static final String NATIVE_API_ADD_DOWNLOAD_QUEUE = "addDownloadQueue";
    static final String NATIVE_API_ADD_NOTIFY_DATA = "addNotifyData";
    static final String NATIVE_API_APPLY_SETTINGS = "applySettings";
    static final String NATIVE_API_CLEAR_DOWNLOAD_QUEUE = "clearDownloadQueue";
    static final String NATIVE_API_CLREA_DATA_POPUPSHOW = "cleardata_popup";
    static final String NATIVE_API_GET_DOWNLOAD_QUEUE = "getDownloadQueue";
    static final String NATIVE_API_GET_MAP_DATA_DOWNLOADPROGRESS = "getdownloadMapDataProgress";
    static final String NATIVE_API_GET_MAP_DATA_TRANSFERPROGRESS = "gettransferMapDataProgress";
    static final String NATIVE_API_REMOVE_NOTIFY_DATA = "removeNotifyData";
    static final String NATIVE_API_SEND_ASYNC_REQUEST = "sendAsyncRequest";
    public static final String NOTIFY_ACCESSORY_INFORMATION = "accessoryInformation";
    public static final String NOTIFY_ACCESSORY_TRANSFER_PROGRESS = "accessoryFileTransferProgress";
    public static final String NOTIFY_ACCESSORY_TRANSFER_STATUS = "accessoryTransferStatus";
    public static final String NOTIFY_AVAILABLE_MAP_REGIONS = "availableMapRegions";
    public static final String NOTIFY_CURRENT_MAP_DETAILS = "currentMapDetails";
    public static final String NOTIFY_DOWNLOAD_STATUS = "downloadStatus";
    public static final String NOTIFY_ERROR = "error";
    public static final String NOTIFY_FILE_TRANSFER_FAILURE = "notifyFileTransferFailure";
    public static final String NOTIFY_MAP_SUBSCRIPTION_DETAILS = "mapSubscriptionDetails";
    public static final String NOTIFY_MAP_SUBSCRIPTION_EXPIRY_STATUS = "mapSubscriptionExpiryStatus";
    public static final String NOTIFY_NOTIFY = "notify";
    public static final String NOTIFY_REGIONS_DOWNLOAD_PROGRESS = "regionsDownloadProgress";
    public static final String NOTIFY_REGION_UPDATE_AVAILABLE = "regionUpdateAvailable";
    public static final String QUERY_AUTO_DOWNLOAD_FLAG = "queryAutoDownloadFlag";
    public static final String QUERY_AUTO_UPDATE_FLAG = "queryAutoUpdateFlag";
    public static final String QUERY_DOWNLOAD_CHANNEL = "queryDownloadChannel";
    public static final String QUERY_MAP_UPDATE_FLAG = "queryMapUpdateFlag";
    public static final String QUERY_NETWORK_CONNECTION_MODE = "queryNetworkConnectivityMode";
    public static final String QUERY_REGION_SETTINGS = "queryRegionSettings";
    public static final String TOM_TOM_SERVICE_IDENTIFIER_Gen3 = "com.hac.mapService.TomTom";
    public static final String TOM_TOM_SERVICE_IDENTIFIER_Gen4 = "com.hac.mapService.TomTom.Gen4";
    public static final String TOM_TOM_SERVICE_IDENTIFIER_Gen5 = "com.hac.mapService.TomTom.Gen5";
    public static final ArrayList<String> TOM_TOM_SERVICE_IDENTIFIER_LIST;

    static {
        ArrayList<String> arrayList = new ArrayList<>();
        TOM_TOM_SERVICE_IDENTIFIER_LIST = arrayList;
        arrayList.add("com.hac.mapService.TomTom");
        arrayList.add("com.hac.mapService.TomTom.Gen4");
        arrayList.add("com.hac.mapService.TomTom.Gen5");
    }
}
